apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: content-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: content-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1
